// Optimized icon system with Lucide React icons and custom SVG sprites
// This replaces the 49KB icons.tsx file with a much smaller, tree-shakeable system

export * from './custom-icons';
// Re-export specific icons to maintain backwards compatibility
export {
  BoxIcon,
  DeltaIcon,
  LogsIcon,
  PythonIcon,
  TerminalWindowIcon,
  VercelIcon,
} from './custom-icons';
export * from './lucide-icons';
export {
  ArrowUpIcon,
  AttachmentIcon,
  BotIcon,
  CheckCircleFillIcon,
  ChevronDownIcon,
  ClockRewindIcon,
  CodeIcon,
  CopyIcon,
  CrossIcon,
  CrossSmallIcon,
  DownloadIcon,
  EyeIcon,
  FileIcon,
  FullscreenIcon,
  GitIcon,
  GlobeIcon,
  GPSIcon,
  HomeIcon,
  ImageIcon,
  InfoIcon,
  InvoiceIcon,
  LineChartIcon,
  LoaderIcon,
  LockIcon,
  MenuIcon,
  MessageIcon,
  MoreHorizontalIcon,
  MoreIcon,
  PaperclipIcon,
  PencilEditIcon,
  PenIcon,
  PlayIcon,
  PlusIcon,
  RedoIcon,
  RouteIcon,
  ShareIcon,
  SidebarLeftIcon,
  SparklesIcon,
  StopIcon,
  SummarizeIcon,
  TerminalIcon,
  ThumbDownIcon,
  ThumbUpIcon,
  TrashIcon,
  UndoIcon,
  UploadIcon,
  UserIcon,
  WarningIcon,
} from './lucide-icons';
export * from './provider-icons';
